sudo: false
branches:
  only:
  - develop
language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
install: npm install
before_script: grunt build
after_success:
- openssl aes-256-cbc -K $encrypted_71233ebdee90_key -iv $encrypted_71233ebdee90_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
- echo -e "Host git.wpengine.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 .travis/deploy_key
- eval `ssh-agent -s`
- ssh-add .travis/deploy_key
- git config user.name "Automated deploy by Travis-CI"
- git config user.email "deploy@travis-ci.org"
- git checkout -b deploy-branch
- git commit -a -m 'build assets'
- git remote add deploy git@git.wpengine.com:production/lsbtest.git
- git push --force deploy deploy-branch:master
