sudo: false
branches:
  only:
  - travis
language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
install: npm install
before_script: grunt build
after_success:
- openssl aes-256-cbc -K $encrypted_612d16cf7c09_key -iv $encrypted_612d16cf7c09_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
- echo -e "Host git.wpengine.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 .travis/deploy_key.pem
- ls -lah .travis/
- eval `ssh-agent -s`
- ssh-add .travis/deploy_key.pem
- git remote add deploy git@git.wpengine.com:production/lsbtest.git
- git push deploy
